UCF/UCF-Degree-CPT-Plugin

admin/ucf-degree-admin.php, gulpfile.js, includes/ucf-degree-program-type-tax.php, package.json, src/js/ucf-degree-admin.js, static/js/ucf-degree-admin.min.js, ucf-degree-cpt.php
Creating the alias and color meta fields for the program_types custom post type.
=> Meta fields

includes/ucf-degree-posttype.php, includes/ucf-degree-utils.php, ucf-degree-cpt.php
Added some additional helper functions and filters to make use a little easier.
=> Helper classes

common/ucf-degree-career-paths-common.php, common/ucf-degree-list-common.php, includes/ucf-degree-utils.php, shortcodes/ucf-degree-career-paths-shortcode.php, shortcodes/ucf-degree-list-shortcode.php, ucf-degree-cpt.php
Created simple shortcodes for listing both degrees (with some filtering options) as well as Career Paths. Both are currently very simple, with very simplistic styles that can be overridden in the Online-Theme (where they will initially be used).
=> Shortcodes

includes/ucf-degree-utils.php
=> Added taxonomy + term appending to ucf_degree_append_meta()

includes/ucf-degree-api.php, ucf-degree-cpt.php
Corrected bug in field registration and added thumbnail field to output.
=> Corrected bug in field registration and added thumbnail field to output.

includes/ucf-degree-api.php, includes/ucf-degree-utils.php
Added some custom filters for doing a very specific search for degrees. Whenever the `degree_search` param is present multiple additional tables will be joined, additional where clauses and then a group by statement added. This enhancement is meant to provide a more usable search api for the typeahead component.
=> Typeahead query

common/ucf-degree-career-paths-common.php, common/ucf-degree-list-common.php, includes/ucf-degree-utils.php, shortcodes/ucf-degree-career-paths-shortcode.php, shortcodes/ucf-degree-list-shortcode.php
- Replaces filters with actions for shortcode-related markup so that hooks have access to the data passed to them (instead of the formatted output).  Fixed subsequent issues with output buffer weirdness.
- Wrapped grouped degree lists in another div by default for easier styling in themes
- Fixed some undefined index notices (https://github.com/UCF/UCF-Degree-CPT-Plugin/compare/shortcode-fixes#diff-a01a82ecc41b85c5706d7713c745c515R43)
=> Shortcode fixes

admin/ucf-degree-config.php, includes/ucf-degree-api.php
Bug Fixes:
* Updated to detect if the now built-in REST API is available.
Enhancements:
* Added postmeta to the meta field of the api.
=> Rest api updates

includes/ucf-degree-api.php, includes/ucf-degree-search-api.php, ucf-degree-cpt.php
Enhancements:
* Adds a custom rest route specifically for the angular degree search.
* The new rest route returns less information then the standard rest route, hopefully speeding up response times.
=> Degree search api

includes/ucf-degree-search-api.php, includes/ucf-degree-search-custom-filters.php, ucf-degree-cpt.php
Enhancements:
* The degree-search api now orders the results by program_types using the new `order_by-taxonomy`, `order_by_taxonomy_field` and `order_by_taxonomy_order` fields.
=> Added custom filters to allow for order_by_taxonomy

includes/ucf-degree-search-api.php
Enhancements:
* Limit field not supported on the /degrees endpoint.
* New endpoints for retrieving the count of posts per taxonomy when a given `s` query is provided.
=> New Endpoints

includes/ucf-degree-search-api.php
Enhancements:
* Adds additional arguments to the taxonomy counts endpoints.
=> Update to taxonomy counts to add  term

common/ucf-degree-program-types-common.php, ucf-degree-cpt.php
Added a new UCF_Degree_Program_Types_Common class with a helper method for returning a program type's alias or name.
=> Added get_name_or_alias() helper method

admin/ucf-degree-config.php, importers/degree-importer.php, includes/ucf-degree-posttype.php, includes/ucf-degree-utils.php, includes/ucf-degree-wpcli.php, ucf-degree-cpt.php
Enhancements:
* Adds logic to import degrees from the search service
* Adds a configuration option for filtering degrees from the search service (i.e. by college)
* Adds an option to schedule the import via wp-cron (the actual logic for adding the wp-cron task still needs to be written)
* Adds some hooks that should allow the import process to be extended for a specific site's needs.
=> Degree importer

includes/ucf-degree-wpcli.php, ucf-degree-cpt.php
Bug Fixes:
* Corrected #26 by updating the class name to something more unique.
* Corrected #15 by placing the code into a named function
* Corrected #14 by placing the activation hooks into the conditional statement.
=> General Clean Up

common/ucf-degree-career-paths-common.php, common/ucf-degree-list-common.php, shortcodes/ucf-degree-career-paths-shortcode.php, shortcodes/ucf-degree-list-shortcode.php
Converts layout actions for degree lists and career path lists to filters.  Also consolidates arguments passed to degree list layout functions, and adds missing layout support for the degree-list shortcode.
=> Layout filters

includes/ucf-degree-search-api.php
Enhancements:
* Added `fullname` field to colleges (i.e. College of something something)
* Added `plural` field to program types.
=> More Details!

importers/degree-importer.php
- Renamed `get_catalog_url` method to `get_uc_catalog_url` for clarity
- Updated `get_uc_program_type` to account for certificates, articulated and accelerated programs properly, and modified program type checking in `get_uc_catalog_url` to be more straightforward (direct string match vs checking for a substring match).  Should fix issues with a lot of degrees not having catalog pdfs defined.
- Removed the college matching in the main catalog match if-statement.  Doing this makes the program matching logic more consistent with how we check for existing degree posts, and fixes a couple of edge cases where a program with one college defined in the undergraduate catalog feed, but two colleges in the search service data, could result in the program's catalog pdf getting set to an empty value, …
=> Undergraduate catalog matching improvements

includes/ucf-degree-posttype.php
* Enhancements:
* Updated degrees to be hierarchical like pages.
=> Hierarchy updates

includes/ucf-degree-search-api.php
Enhancements:
* Added function that reorders results based on parent/child relationship.
=> Api update

importers/degree-importer.php
- Updated how degree total is calculated in importer success message
- Updated import exception messages for helpfulness
=> Minor import success/error message updates

includes/ucf-degree-search-api.php, includes/ucf-degree-search-custom-filters.php
Enhancements/Bugs:
* Update the custom order_by_taxonomy to only group the degrees by child terms (so no Group for Undergraduate Program or Graduate Program).
* Update the terms to match what we'll be using going forward.
=> Order By Update

includes/ucf-degree-search-api.php
Bug Fixes:
* Removed IDs from the return values.
=> Removed IDs as index from program-types endpoint

includes/ucf-degree-search-api.php
Bug Fixes:
* Updated logic so that children degrees are organized by children program_types, unless there is only one program_type assigned.
=> Bug parent prg type

includes/ucf-degree-search-api.php
Enhancements:
* Updates the `ucf-degree-search/v1/program-types/` API to account for hierarchy.
=> Updated degree search program-type route

importers/degree-importer.php
Enhancements:
* Updated endpoint for programs to allow for filtering.
=> Updated endpoint to allow for filtering

importers/degree-importer.php, includes/ucf-degree-wpcli.php
Adds a `verbose` option to the degree importer, which will return a more detailed set of changes for existing degrees that have been modified during the import process once the import finishes successfully.
=> Verbose import logging

includes/ucf-degree-api.php
Enhancements:
* Adds the `program_types` and `colleges` GET parameters to the `/wp/v2/degrees/` endpoint.
=> Add GET parameters

includes/ucf-degree-search-api.php
Enhancements:
* Adds very simple college schema to each result in the `ucf-degree-search/v1/degrees/` endpoint.
=> Add colleges output

includes/ucf-degree-api.php, includes/ucf-degree-interest-tax.php, includes/ucf-degree-posttype.php, ucf-degree-cpt.php
Enhancements:
* Added `interests` custom taxonomy.
* Added `interests` as an available filter and additional field on the `/degrees` API endpoints.
=> Interest taxonomy

includes/ucf-degree-career-path-tax.php, includes/ucf-degree-interest-tax.php, includes/ucf-degree-utils.php
Enhancements:
* Added capitalization utility function to better support backup values for the `interests_display_text` meta field.
* Added some filter functions to `career_paths` to make it more consistent with what I'm doing on `interests`. Also updated comments on this class/functions.
* Added the `interests_display_text` meta field forms so they're baked into the plugin.
=> Interests term display field

common/ucf-degree-list-common.php
Bug Fixes:
* Added missing quote to class attribute on the `ucf-degree-list-title` heading.
=> Added missing quote

importers/degree-importer.php
Enhancements:
* Updated the degree importer to get the tuition data from the `program` object in the search service (recently added).
=> Updated importer to get tuition data

importers/degree-importer.php
Enhancements:
* Adds a filter for adjusting the tuition string.
=> Added filter for formatting tuition string

admin/ucf-degree-config.php, admin/ucf-degree-messages.php, common/ucf-degree-common.php, includes/ucf-degree-posttype.php, ucf-degree-cpt.php
Enhancements:
* Adds the `degree_tuition_skip` field which, when checked, will add a `TuitionOverride` object to the search service via an API call.
* Adds admin messages for letting the user know if the API call is successful.
=> Added a tuition skip field and added api capabilities

importers/degree-importer.php
Bug Fixes:
* Updated importer to account for hierarchical taxonomies, which can't be added by ID.
=> Taxonomy import fix

importers/degree-importer.php
Updated the degree importer to remove all taxonomy term associations for each set of taxonomy terms being loaded in from the search service so that stale term data gets cleared out.
=> Degree import: Remove stale taxonomy term associations

importers/degree-importer.php
**Description**
Updates the degree importer logic to ignore degrees that have the "Ignore on Import" flag checked. When checked, the degree will not be processed at all during the import and will be counted and reported as "Ignored" in the stats.
**Motivation and Context**
Previously, this setting was causing a degree to not be deleted during import, but it was still being processed and the data was refreshed from the search service. This corrects that bug.
**How Has This Been Tested?**
The importer has been demonstrated to work correctly in dev by manually adding a Career Path term and then running the import. After the import was complete, the custom career path was still there. 
**Types of changes**
**Checklist:**
=> Updated Import Logic

importers/degree-importer.php
**Description**
See title.
**Motivation and Context**
Resolves #114 
**How Has This Been Tested?**
Tested in Dev.
**Types of changes**
**Checklist:**
=> Updated imported college and dept terms to use `name` from search service instead of `full_name`

README.md, api/ucf-degree-api.php, api/ucf-degree-search-api.php, readme.txt, ucf-degree-cpt.php
**Description**
Updated register_rest_route permission_callback param to quiet Notice
**Motivation and Context**
Fix notices
**How Has This Been Tested?**
Tested in DEV
**Types of changes**
**Checklist:**
=> Updated the register_rest_route methods to quiet Notices

importers/degree-importer.php
**Description**
Makes the `existing_post` field of the `UCF_Degree_Import` class public so that is can be accessed in hooks to determine if a post should be updated in certain ways.
**How Has This Been Tested?**
Changes are available in DEV.
**Types of changes**
**Checklist:**
=> Make existing post public so it can be accessed
